name: Build LaTeX Document
on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@v3
        with:
          name: Compiled PDF
          path: main.pdf
